# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

    # Deploy 2 Nodes with two links between them

    config.vm.define "n9k1" do |node|
        node.vm.box = "n9000v"
        node.vm.base_mac = "0800276CEEAA"

        # eth1/1 connected to vboxnet1, auto-config not supported.
        node.vm.network :private_network, virtualbox__intnet: "nxeth1",
          auto_config: false, mac: "0800276CEE15"

        # eth1/2 connected to vboxnet2, auto-config not supported.
        node.vm.network :private_network, virtualbox__intnet: "nxeth2",
          auto_config: false, mac: "0800276CEE16"

        node.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
            v.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
        end
    end

    config.vm.define "n9k2" do |node|
        node.vm.box = "n9000v"
        node.vm.base_mac = "0800276DEEAA"

        # eth1/1 connected to vboxnet1, auto-config not supported.
        node.vm.network :private_network, virtualbox__intnet: "nxeth1",
          auto_config: false, mac: "0800276DEE15"

        # eth1/2 connected to vboxnet2, auto-config not supported.
        node.vm.network :private_network, virtualbox__intnet: "nxeth2",
          auto_config: false, mac: "0800276DEE16"

        node.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
            v.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
        end
    end

end
